import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Alert,
  StatusBar,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useAuth } from '../context/AuthContext';
import { clearHistory } from '../utils/storage';
import { Colors, Spacing, BorderRadius, FontSize, FontWeight } from '../utils/theme';

export default function ProfileScreen() {
  const { user, logout } = useAuth();

  const handleClearHistory = () => {
    Alert.alert(
      'Clear History',
      'Are you sure you want to delete all saved scans? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            await clearHistory();
            Alert.alert('Success', 'History cleared.');
          },
        },
      ]
    );
  };

  return (
    <LinearGradient colors={[Colors.bg, '#0f1a24', Colors.bg]} style={styles.container}>
      <StatusBar barStyle="light-content" />

      <View style={styles.header}>
        <Text style={styles.sectionLabel}>Account</Text>
        <Text style={styles.title}>Profile</Text>
      </View>

      {/* User Info Card */}
      <View style={styles.card}>
        <View style={styles.userInfo}>
          <View style={styles.avatar}>
            <Text style={styles.avatarText}>
              {user?.email?.[0]?.toUpperCase() || '?'}
            </Text>
          </View>
          <View style={styles.userDetails}>
            <Text style={styles.email}>{user?.email || 'Not logged in'}</Text>
            <Text style={styles.status}>Active Session</Text>
          </View>
        </View>
      </View>

      {/* Settings List */}
      <View style={styles.settingsGroup}>
        <Text style={styles.groupLabel}>Settings & Data</Text>

        <TouchableOpacity style={styles.row} onPress={handleClearHistory}>
          <View style={styles.rowLeft}>
            <Text style={styles.rowIcon}>🗑️</Text>
            <Text style={styles.rowText}>Clear Scan History</Text>
          </View>
          <Text style={styles.rowArrow}>›</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[styles.row, styles.rowNoBorder]} onPress={logout}>
          <View style={styles.rowLeft}>
            <Text style={styles.rowIcon}>🚪</Text>
            <Text style={[styles.rowText, { color: Colors.error }]}>Sign Out</Text>
          </View>
        </TouchableOpacity>
      </View>

      <View style={styles.settingsGroup}>
        <Text style={styles.groupLabel}>About</Text>

        <View style={styles.row}>
          <View style={styles.rowLeft}>
            <Text style={styles.rowIcon}>ℹ️</Text>
            <Text style={styles.rowText}>Version</Text>
          </View>
          <Text style={styles.rowValue}>1.0.0 (Experimental)</Text>
        </View>

        <View style={[styles.row, styles.rowNoBorder]}>
          <View style={styles.rowLeft}>
            <Text style={styles.rowIcon}>⚠️</Text>
            <Text style={styles.rowText}>Medical Disclaimer</Text>
          </View>
        </View>
        <Text style={styles.disclaimerText}>
          GlucoScan AI is an experimental application. The glucose and heart rate predictions
          are generated by an AI model analyzing PPG signals and have not been medically validated.
          Do not use this app for medical diagnosis, treatment, or decisions.
        </Text>
      </View>

    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: 60,
  },
  header: {
    marginBottom: Spacing.lg,
  },
  sectionLabel: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.accent,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: Spacing.xs,
  },
  title: {
    fontSize: FontSize.xxxl,
    fontWeight: FontWeight.extrabold,
    color: Colors.textPrimary,
  },
  card: {
    backgroundColor: Colors.bgGlass,
    borderWidth: 1,
    borderColor: Colors.bgGlassBorder,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.xl,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(0,200,180,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,200,180,0.3)',
  },
  avatarText: {
    fontSize: 24,
    fontWeight: FontWeight.bold,
    color: Colors.accent,
  },
  userDetails: {
    flex: 1,
  },
  email: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  status: {
    fontSize: FontSize.sm,
    color: Colors.success,
    fontWeight: FontWeight.medium,
  },
  settingsGroup: {
    marginBottom: Spacing.xl,
  },
  groupLabel: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.xs,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  rowNoBorder: {
    borderBottomWidth: 0,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  rowIcon: {
    fontSize: 20,
  },
  rowText: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    color: Colors.textPrimary,
  },
  rowArrow: {
    fontSize: 20,
    color: Colors.textMuted,
  },
  rowValue: {
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
  },
  disclaimerText: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    lineHeight: 18,
    paddingHorizontal: Spacing.xs,
    marginTop: Spacing.sm,
  },
});
